CREATE TABLE user_name (
	id BIGINT(20) PRIMARY KEY,
    name VARCHAR(15) NOT NULL,
    email VARCHAR(50) NOT NULL,
    pass VARCHAR(50) NOT NULL,
    label VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE lab (
	id BIGINT(20) PRIMARY KEY,
    name VARCHAR(15) NOT NULL,
    label VARCHAR(50) NOT NULL,
    id_user BIGINT(20) NOT NULL,
    FOREIGN KEY (id_user) REFERENCES user(id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE permission (
	id BIGINT(20) PRIMARY KEY,
    label VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;